services:
  - docker

env:
  matrix:
    - DOCKERFILE="Dockerfile-cli" DOCKERPATH="7.0"
    - DOCKERFILE="Dockerfile-fpm" DOCKERPATH="7.0"
    - DOCKERFILE="Dockerfile-cli" DOCKERPATH="7.1"
    - DOCKERFILE="Dockerfile-fpm" DOCKERPATH="7.1"
    - DOCKERFILE="Dockerfile-cli" DOCKERPATH="7.2"
    - DOCKERFILE="Dockerfile-fpm" DOCKERPATH="7.2"
    - DOCKERFILE="Dockerfile-cli" DOCKERPATH="7.3"
    - DOCKERFILE="Dockerfile-fpm" DOCKERPATH="7.3"
    - DOCKERFILE="Dockerfile-cli" DOCKERPATH="7.4"
    - DOCKERFILE="Dockerfile-fpm" DOCKERPATH="7.4"

before_script:
  - docker version

script:
  - docker build -f ./${DOCKERPATH}/${DOCKERFILE} -t ${DOCKERPATH} ./${DOCKERPATH}
