name: Tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        context:
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
        dockerfile:
          - "Dockerfile-fpm"
          - "Dockerfile-cli"
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.dockerfile }}
          push: true
          tags: localhost:5000/local/test:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Check php info
        run: docker run --rm -i localhost:5000/local/test:latest php -i
