name: Tests

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        context:
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
        dockerfile:
          - "Dockerfile-fpm"
          - "Dockerfile-cli"
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ./${{ matrix.dockerfile }}
          push: false
          tags: test:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Check php info
        run: docker run --rm -ti test php -i
